# Generated by Django 3.2 on 2021-04-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationhistory',
            old_name='notification_text',
            new_name='notification_body',
        ),
        migrations.AddField(
            model_name='notificationhistory',
            name='notification_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='notificationhistory',
            name='notification_title',
            field=models.TextField(default='title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='notification_icon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
