# Generated by Django 3.2 on 2021-04-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_notification_body_notificationhistory_notification_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='notification_title',
            field=models.CharField(max_length=150),
        ),
    ]
