# Generated by Django 3.2 on 2021-04-27 11:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notificationhistory_notification_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
