# Generated by Django 3.2 on 2021-04-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_notificationhistory_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationhistory',
            old_name='notification_text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='notificationhistory',
            old_name='notification_icon',
            new_name='icon',
        ),
        migrations.RenameField(
            model_name='notificationhistory',
            old_name='notification_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='notificationhistory',
            old_name='notification_title',
            new_name='title',
        ),
    ]
